### ISSUE TITLE
support for unity 2020(.2)

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Malimbe#63]
## Is your feature request related to a problem?

in unity 2020.2, import zinnia (and thus malimbe) packages, compiled alright, but the inspector has not shown the serialized properties.

for example
![image](https://user-images.githubusercontent.com/22952143/104130017-7f954700-53a9-11eb-8650-a997cc200150.png)

seems fodyweaver is not working.

**Comment by thestonefox** [comment]
I wonder what Unity have done differently to the editor in 2020.2. I bet they've not outlined it in their release notes either

**Comment by fight4dream** [comment]
a restart of unity fixed the problem

**Comment by thestonefox** [comment]
The issue seems to stem from if you upgrade your project from an earlier version of Unity to 2020.2 then the Fody Weavers don't run on the project until you restart Unity and then they seem to work ok.

If you start a fresh project in 2020.2 then the Fody Weavers work first time.

Not sure what is causing this, but a restart of Unity after upgrading project fixes it so lets leave this as a "wont fix"
